const languages = {
    "ara_AE": "Arabic (UAE)",
    "ben_IN": "Bengali (India)",
    "ben_BD": "Bengali (Bangladesh)",
    "dan": "Danish",
    "ell": "Greek",
    "eng_GB": "English (UK)",
    "eng_US": "English (US)",
    "fin": "Finnish",
    "fra": "French",
    "ger": "German",
    "ind": "Indonesian",
    "ita": "Italian",
    "jpn": "Japanese",
    "kan": "Kannada",
    "kor": "Korean",
    "mal": "Malayalam (India)",
    "nld": "Dutch",
    "nor": "Norwegian",
    "pol": "Polish",
    "por_BR": "Portuguese (Brazil)",
    "por_PT": "Portuguese (Portugal)",
    "ron": "Romanian",
    "rus": "Russian",
    "spa": "Spanish",
    "spa_AR": "Spanish (Argentina)",
    "spa_MX": "Spanish (Mexico)",
    "spa_ES": "Spanish (Spain)",
    "swe": "Swedish",
    "tam": "Tamil",
    "tel": "Telugu",
    "tha": "Thai",
    "tur": "Turkish",
    "zho_CN": "Chinese (China)",
    "zho_TW": "Chinese (Taiwan)"
};
